# Generated by Django 3.2 on 2021-05-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='second',
        ),
    ]
