# Generated by Django 3.2 on 2021-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=122)),
                ('uom', models.CharField(max_length=122)),
                ('manufac', models.CharField(max_length=122)),
                ('pscheme', models.CharField(choices=[('1', 'PS1'), ('2', 'PS2'), ('3', 'PS3')], max_length=1)),
            ],
        ),
    ]
