# Generated by Django 3.2.6 on 2021-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20210608_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemcode',
            field=models.CharField(default='00', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufac',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
