# Generated by Django 3.2.6 on 2021-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_purchesinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchesinvoice',
            name='batchno',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
