# Generated by Django 3.2.6 on 2021-09-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_purchesinvoice_batchno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_code',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
