# Generated by Django 3.2.6 on 2021-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_customer_cust_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='puchaseprice',
            field=models.DecimalField(decimal_places=2, default=230, max_digits=8),
        ),
    ]
