# Generated by Django 3.2.6 on 2021-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_item_puchaseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='puchaseprice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
