# Generated by Django 3.2.6 on 2021-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_alter_item_puchaseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
