# Generated by Django 3.2.6 on 2021-09-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_purchesinvoice_vengstin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gst',
            new_name='gstn',
        ),
    ]
