# Generated by Django 3.2.6 on 2021-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_rename_gst_customer_gstn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchesinvoice',
            name='cgstamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchesinvoice',
            name='igstamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchesinvoice',
            name='sgstamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchesinvoice',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
