# Generated by Django 3.2.6 on 2021-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0016_auto_20210917_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricingscheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricingscheme', models.CharField(max_length=20)),
                ('lowerlimit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uperlimit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchaseprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profitmarginfactor', models.DecimalField(decimal_places=3, max_digits=8)),
                ('salseprice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
