# Generated by Django 3.2.6 on 2021-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0018_pricingscheme_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchesinvoice',
            name='batchno',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='purchesinvoice',
            name='invoiceno',
            field=models.CharField(max_length=100000),
        ),
    ]
