# Generated by Django 3.2.6 on 2021-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0024_alter_purchesinvoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salseinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
