# Generated by Django 3.2.6 on 2021-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0025_alter_salseinvoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
