# Generated by Django 3.2.6 on 2021-09-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0027_alter_paymentvoucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='unitprice',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
