# Generated by Django 3.2.6 on 2021-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0028_alter_paymentvoucher_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchesinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchesinvoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchesinvoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchesinvoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchesinvoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchesinvoice',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
