# Generated by Django 3.2.6 on 2021-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0029_auto_20211018_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='puchaseprice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='unitprice',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='lowerlimit',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='profit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='profitmarginfactor',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='purchaseprice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='salseprice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='uperlimit',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salseinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salseinvoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salseinvoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salseinvoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salseinvoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salseinvoice',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
